spring.application.name=protube-back
server.port=8080

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.profiles.active=@spring.profiles.active@

jwt.secret=d6f8a9b2c3d4e5f6718a9b2c3d4e5f6718a9b2c3d4e5f6718a9b2c3d4e5f671
jwt.expiration=3600000


# Before running the process you must have this system-level environment variable set: ENV_PROTUBE_STORE_DIR
# It must hold the absolute path to the directory containing the videos (and any other file-based storage)
pro_tube.store.dir=${ENV_PROTUBE_STORE_DIR}

# Disable H2 console
spring.h2.console.enabled=false

#---
spring.config.activate.on-profile=dev
spring.datasource.url=jdbc:postgresql://localhost:5432/protube
pro_tube.load_initial_data=true
spring.datasource.username=admin
spring.datasource.password=grup102
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.prefix=classpath:/templates/
spring.security.jwt.secret=your-secret-key

#---
spring.config.activate.on-profile=prod
pro_tube.load_initial_data=false
spring.datasource.url=jdbc:postgresql://localhost:5432/protube
spring.datasource.username=admin
spring.datasource.password=grup102
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.prefix=classpath:/static/
spring.security.jwt.secret=your-secret-key

spring.mvc.static-path-pattern=/media/**
logging.level.org.springframework.web=DEBUG